name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Primos Test
      id: primos-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 6
        setup-command: sudo -H pip3 install pytest
    - name: Hello Test
      id: hello-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 14
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRIMOS-TEST_RESULTS: "${{steps.primos-test.outputs.result}}"
        HELLO-TEST_RESULTS: "${{steps.hello-test.outputs.result}}"
      with:
        runners: primos-test,hello-test
